### PR TITLE
fix deprecated akka shutdown

### LINKED ISSUE #1: Improve Akka Shutdown
Technical debt from the Akka upgrade. Fix the Akka shutdown logic in Main. It looks like this will also affect BaseActorTest.

### PR DESCRIPTION
**Pull request by BrandonArp**
Fixes #1

### CODE REVIEW

File: src/main/java/com/arpnetworking/metrics/mad/Main.java [hunk 1]
```diff
@@ -264,14 +267,19 @@ private void shutdownActors() {
...
-    @SuppressWarnings("deprecation")
     private void shutdownAkka() {
         LOGGER.info().setMessage("Stopping akka").log();
 
         if (_actorSystem != null) {
-            _actorSystem.shutdown();
-            _actorSystem.awaitTermination();
+            Future<Terminated> terminate = _actorSystem.terminate();
+            try {
+                Await.result(terminate, Duration.create(5, TimeUnit.MINUTES));
```
Comment (vjkoskela) [inline src/main/java/com/arpnetworking/metrics/mad/Main.java]: 5 minutes? This seems like a bad idea.

Comment (BrandonArp) [inline src/main/java/com/arpnetworking/metrics/mad/Main.java]: Why?  Before it was waiting forever.  At least now it's bounded.
